import { CaptureItem, KnowledgeSignal, TopicItem } from "@/types";

export const MOCK_TOPICS: TopicItem[] = [
  { id: "ai-agents", name: "AI Agents", count: 42, description: "Agent memory, autonomous workflows, LLM orchestration" },
  { id: "product", name: "Product", count: 31, description: "Zero-organization UX, personal intelligence interfaces" },
  { id: "retail", name: "Retail", count: 18, description: "Autonomous procurement, smart supply chain, POS AI" },
  { id: "technology", name: "Technology", count: 16, description: "Vector DBs, embedding models, local inference" },
  { id: "ideas", name: "Ideas", count: 12, description: "Random thoughts, quick insights dropped from mobile" },
];

export const MOCK_CAPTURES: CaptureItem[] = [
  {
    id: "cap-01",
    type: "link",
    source: {
      channel: "line",
      provider: "Facebook",
      url: "https://facebook.com/groups/ai-builders/posts/98231",
      senderName: "Personal LINE",
    },
    title: "Agentic Commerce is moving into retail procurement",
    summary:
      "Several retailers are experimenting with autonomous procurement agents capable of comparing suppliers, negotiating terms and auto-generating purchase orders.",
    keyIdeas: [
      "Autonomous supplier comparison and multi-attribute evaluation",
      "Dynamic negotiation bots acting within human-approved budget thresholds",
      "End-to-end ERP integration with automated purchase order generation",
    ],
    topics: ["AI Agents", "Retail", "Procurement"],
    entities: ["Autonomous Agents", "Procurement ERP", "Supply Chain AI", "B2B Commerce"],
    capturedAt: "Yesterday at 18:42",
    status: "ready",
    importanceScore: 0.94,
    whyItMatters: "Related to 4 items you've saved about AI agents and retail.",
    relatedItemIds: ["cap-02", "cap-03", "cap-06", "cap-07"],
    category: "knowledge",
    rawText:
      "แชร์เคส Agentic Commerce ในวงการ Retail ตอนนี้ retailer หลายเจ้าเริ่มทดสอบ procurement agent ที่สามารถ compare supplier, negotiate terms อัตโนมัติ และสร้าง purchase order ได้เองโดยตรง ไม่ต้องรอ human buyer มานั่งคลิกทีละขั้นตอน",
  },
  {
    id: "cap-02",
    type: "image",
    source: {
      channel: "line",
      provider: "Facebook Screenshot",
      senderName: "Personal LINE",
    },
    title: "AI Agent Architecture: Planner, Memory & Tool Execution",
    summary:
      "Architecture diagram breaking down autonomous agent stack into multi-tier memory (episodic + semantic), planner feedback loop, and sandboxed tool workers.",
    keyIdeas: [
      "Separation between fast context memory and long-term episodic retrieval",
      "Planner-evaluator reflection loop before calling external tool APIs",
      "Sandboxed runtime execution environment for untrusted outputs",
    ],
    topics: ["AI Agents", "Architecture", "Technology"],
    entities: ["Planner Loop", "Episodic Memory", "Vector Index", "Tool Sandbox"],
    capturedAt: "2 minutes ago",
    status: "ready",
    importanceScore: 0.91,
    whyItMatters: "Matches your recent focus on long-term agent memory structures.",
    relatedItemIds: ["cap-01", "cap-04", "cap-05", "cap-08"],
    category: "knowledge",
    thumbnailUrl: "/mock-diagram.svg",
    rawText: "[Image Capture] Architecture diagram showing: User Intent → Planner → Context Injector (Semantic Memory + Short-term buffer) → Tool Executor → Reflection loop → Output.",
  },
  {
    id: "cap-03",
    type: "link",
    source: {
      channel: "line",
      provider: "medium.com",
      url: "https://medium.com/@techlead/the-new-architecture-of-personal-ai-891",
      senderName: "Personal LINE",
    },
    title: "The New Architecture of Personal AI",
    summary:
      "Personal AI systems increasingly separate reasoning, memory, and tool execution into distinct decoupled micro-layers rather than one monolithic prompt.",
    keyIdeas: [
      "Memory as a personal data layer that persists across model upgrades",
      "Zero-tagging input pipelines with ambient background classification",
      "Just-in-time contextual synthesis based on daily rhythm",
    ],
    topics: ["AI", "Personal Intelligence", "Product"],
    entities: ["Personal AI", "Ambient Ingestion", "Decoupled Memory"],
    capturedAt: "18 minutes ago",
    status: "ready",
    importanceScore: 0.88,
    whyItMatters: "Directly relates to the MINDROP zero-organization concept.",
    relatedItemIds: ["cap-01", "cap-04", "cap-05"],
    category: "knowledge",
    rawText: "The future of personal AI won't be another chatbot window. It will be an ambient intelligence layer that indexes everything you observe, reads between the lines, and synthesizes what matters before you ask.",
  },
  {
    id: "cap-04",
    type: "text",
    source: {
      channel: "line",
      provider: "Direct Thought",
      senderName: "Personal LINE",
    },
    title: "ทำ personal knowledge ที่ไม่ต้องจัด folder เอง",
    summary:
      "Product idea about zero-organization personal knowledge management. Users just drop thoughts, photos, or links, and AI autonomously contextualizes and resurfaces them.",
    keyIdeas: [
      "Eliminate inbox anxiety: never make the user clean folders or organize tags",
      "Resurface based on relevance, not chronology or tag trees",
      "LINE as the universal zero-friction capture gateway",
    ],
    topics: ["Product", "Ideas", "AI"],
    entities: ["Zero-Org PKM", "LINE Gateway", "Contextual Resurfacing"],
    capturedAt: "Yesterday at 14:15",
    status: "ready",
    importanceScore: 0.95,
    whyItMatters: "Core vision note for the MINDROP prototype.",
    relatedItemIds: ["cap-03", "cap-05"],
    category: "idea",
    rawText: "ทำ personal knowledge ที่ไม่ต้องจัด folder เอง แค่โยนทุกอย่างลง LINE แล้วให้ AI ทำ semantic indexing, cluster theme, และเตือนตอนที่เราต้องการใช้งานจริงๆ",
  },
  {
    id: "cap-05",
    type: "link",
    source: {
      channel: "line",
      provider: "Arxiv / Research",
      url: "https://arxiv.org/abs/2402.0981",
      senderName: "Personal LINE",
    },
    title: "Building Long-Term Memory for Autonomous Agents",
    summary:
      "Comprehensive research paper examining episodic memory consolidation, token compression, and memory decay curves for AI agents.",
    keyIdeas: [
      "Episodic memory decay mimicking human hippocampus consolidation",
      "Semantic indexing with contextual relevance weighting",
      "Cross-session entity linking and automatic relationship updates",
    ],
    topics: ["AI Agents", "Technology", "Memory"],
    entities: ["Episodic Memory", "Semantic Retrieval", "Context Compression", "Hippocampus Model"],
    capturedAt: "3 months ago",
    status: "ready",
    importanceScore: 0.96,
    whyItMatters: "Your recent saves increasingly mention episodic memory, semantic retrieval and agent context management.",
    relatedItemIds: ["cap-01", "cap-02", "cap-03", "cap-04", "cap-08"],
    category: "knowledge",
    resurfacedContext: {
      originalDate: "3 months ago",
      triggerReason: "You saved this before your recent interest in Agent Memory. Connects with 6 things you've captured recently.",
      connectedItemCount: 6,
    },
    rawText: "Abstract: We propose an agent memory architecture combining dense retrieval, episodic event replay, and proactive memory summarization...",
  },
  {
    id: "cap-06",
    type: "file",
    source: {
      channel: "line",
      provider: "PDF Document",
      senderName: "Personal LINE",
    },
    title: "Southeast Asia Retail Modernization Report 2026",
    summary:
      "Analysis on how modern trade in ASEAN is shifting toward automated restocking, real-time inventory AI, and localized supply chain resilience.",
    keyIdeas: [
      "73% of tier-1 retail operators piloting autonomous reordering",
      "Shift from manual inventory counts to computer vision shelf monitoring",
      "Integration of local supplier APIs for dynamic delivery routing",
    ],
    topics: ["Retail", "Technology", "Product"],
    entities: ["ASEAN Retail", "Inventory AI", "Modern Trade", "Supply Chain"],
    capturedAt: "3 days ago",
    status: "ready",
    importanceScore: 0.82,
    whyItMatters: "Provides market context for your retail procurement AI notes.",
    relatedItemIds: ["cap-01", "cap-07"],
    category: "reference",
    rawText: "[PDF Attachment: sea_retail_report_2026.pdf] Executive Summary: Retailers across Thailand, Indonesia, and Vietnam are accelerating autonomous logistics...",
  },
  {
    id: "cap-07",
    type: "text",
    source: {
      channel: "line",
      provider: "Direct Thought",
      senderName: "Personal LINE",
    },
    title: "Insight: Retailers care about supplier trust more than 1% price cut",
    summary:
      "Note from conversation with retail director: Autonomous procurement agents need supplier reliability scores, not just cheapest price optimization.",
    keyIdeas: [
      "Procurement AI must optimize for on-time fulfillment reliability first",
      "Price negotiation must respect historical relationship and SLA terms",
    ],
    topics: ["Retail", "Ideas", "AI Agents"],
    entities: ["Procurement SLA", "Supplier Trust Score", "Retail Director Feedback"],
    capturedAt: "4 days ago",
    status: "ready",
    importanceScore: 0.79,
    whyItMatters: "Critical constraint to feed into agentic procurement workflows.",
    relatedItemIds: ["cap-01", "cap-06"],
    category: "idea",
    rawText: "คุยกับพี่ retail วันนี้ ได้ insight ว่า procurement agent ห้าม optimize แค่ราคาถูกที่สุดอย่างเดียว แต่ต้องดู historical SLA กับ supplier trust score ด้วย เพราะของไม่มาส่งเสียหายหนักกว่าส่วนต่าง 1%",
  },
  {
    id: "cap-08",
    type: "image",
    source: {
      channel: "line",
      provider: "LINE Photo",
      senderName: "Personal LINE",
    },
    title: "Whiteboard Sketch: Context Compression Pipeline",
    summary:
      "Diagram showing multi-stage token compression for long memory retrieval: hierarchical clustering, key sentence extraction, and sparse vector retrieval.",
    keyIdeas: [
      "Hierarchical cluster summarization before LLM injection",
      "Sparse + dense hybrid search to balance exact IDs and abstract concepts",
    ],
    topics: ["AI Agents", "Technology", "Architecture"],
    entities: ["Token Compression", "Hybrid Search", "Context Window"],
    capturedAt: "5 days ago",
    status: "ready",
    importanceScore: 0.85,
    whyItMatters: "Technical blueprint directly supporting memory resurfacing.",
    relatedItemIds: ["cap-02", "cap-05"],
    category: "knowledge",
    thumbnailUrl: "/mock-diagram.svg",
    rawText: "[Whiteboard Photo] Step 1: Raw text → Tokenizer → Vector Index. Step 2: Context Compressor → 80% Token Reduction → LLM Prompt Buffer.",
  },
  {
    id: "cap-09",
    type: "link",
    source: {
      channel: "line",
      provider: "Twitter / X",
      url: "https://x.com/karpathy/status/1792348",
      senderName: "Personal LINE",
    },
    title: "Thoughts on LLM as CPU, Context Window as RAM, Files as Disk",
    summary:
      "Perspective framing LLM operating systems: context window is active working RAM, external vector DBs are NVMe storage, and personal agents act as kernel schedulers.",
    keyIdeas: [
      "Personal AI OS abstraction layer",
      "Context management as paging and virtual memory",
    ],
    topics: ["Technology", "AI Agents", "Product"],
    entities: ["LLM OS", "Virtual Memory", "Context Paging"],
    capturedAt: "6 days ago",
    status: "ready",
    importanceScore: 0.89,
    whyItMatters: "Foundational mental model for MINDROP system design.",
    relatedItemIds: ["cap-02", "cap-03", "cap-05"],
    category: "knowledge",
    rawText: "Thinking about LLMs as the CPU of a new operating system. The context window is RAM, tools are peripherals, and vector memory is secondary storage...",
  },
  {
    id: "cap-10",
    type: "text",
    source: {
      channel: "line",
      provider: "Direct Thought",
      senderName: "Personal LINE",
    },
    title: "LINE Webhook Ingestion Latency Budget",
    summary:
      "Technical note: When user drops image/link into LINE, respond immediately with receipt within 500ms, then async stream background embedding.",
    keyIdeas: [
      "Fast LINE ack (<500ms) with typing status",
      "Asynchronous BullMQ worker for OCR, URL scraping, and embedding",
    ],
    topics: ["Technology", "Product"],
    entities: ["LINE Webhook", "Async Ingestion", "Background Worker"],
    capturedAt: "Just now",
    status: "processing",
    importanceScore: 0.70,
    whyItMatters: "Ensures capture feels zero-effort with zero UI delay.",
    relatedItemIds: ["cap-04"],
    category: "idea",
    rawText: "LINE bot UX: ต้องตอบกลับ user เร็วมาก ไม่เกิน 500ms ให้รู้ว่าได้รับแล้ว ส่วนการ summarize / OCR / embedding ให้ทำ background async",
  },
];

export const MOCK_WEEKLY_SIGNAL: KnowledgeSignal = {
  id: "sig-week-33",
  title: "This week's signal",
  description: "You captured 27 things.",
  period: "Aug 10 – Aug 17",
  supportingItemIds: ["cap-01", "cap-02", "cap-03", "cap-04", "cap-05", "cap-06", "cap-07"],
  keyTrends: [
    "AI agents are moving from chat → execution",
    "Personal memory is becoming infrastructure",
    "Retail AI is shifting toward autonomous workflows",
  ],
};
